---
title: "Time"
author: "Jake Eisaguirre"
date: "11/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

remove.packages("clockify")
remotes::install_github("bbest/clockify")
```

```{r}

# get libraries
if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
  library(tidyverse)
}
librarian::shelf(
  bbest/clockify,
  dplyr, DT, ggplot2,
  quiet = TRUE)
# CHANGE THESE VARIABLES!
api_txt <- "/Users/JaketheBoss/Desktop/API.txt"
project_name <- "mk-waves"

# use API key to authenticate
CLOCKIFY_API_KEY <- readLines(api_txt)
set_api_key(CLOCKIFY_API_KEY)

# get data
d_projects <- projects() %>% 
      select(project_id, project_name)
d_users <- users() %>% 
      select(user_id, user_name)
d_times <- time_entries(concise = F) %>% 
  left_join(
    d_projects, by = "project_id") %>% 
  left_join(
    d_users, by = "user_id")

# show table
d_times %>% 
  select(
    user_name, project_name, 
    time_start, duration, description) %>% 
  arrange(user_name, project_name, time_start) %>% 
  datatable() %>%
  formatRound(columns=c('duration'), digits=3)
```

```{r}
# plot ALL
plot_burndown(
  d_times,
  beg = as.Date("2021-10-31"), # day before
  end = as.Date("2021-11-21"), # day after
  hrs = 20)
# table ALL
datatable(d_times)
```
### 1. Import Data
```{r}
task <- "Import Data"
d_task <- d_times %>%
  filter(task_name == !!task)
plot_burndown(
  d_task,
  beg = as.Date("2021-10-31"), # day before
  end = as.Date("2021-11-08"), # day after
  hrs = 3)
datatable(d_task)
```
### 2. Inspect Data
```{r}
task <- "Inspect Data"
d_task <- d_times %>%
  filter(task_name == !!task)
plot_burndown(
  d_task,
  beg = as.Date("2021-10-31"), # day before
  end = as.Date("2021-11-07"), # day after
  hrs = 4)
datatable(d_task)
```
### 3. Tidy Data
```{r}
task <- "Tidy Data"
d_task <- d_times %>%
  filter(task_name == !!task)
plot_burndown(
  d_task,
  beg = as.Date("2021-10-31"), # day before
  end = as.Date("2021-11-07"), # day after
  hrs = 10)
datatable(d_task)
```
### 4. Transform Data
```{r}
task <- "Transform Data"
d_task <- d_times %>%
  filter(task_name == !!task)
plot_burndown(
  d_task,
  beg = as.Date("2021-10-31"), # day before
  end = as.Date("2021-11-07"), # day after
  hrs = 1)
datatable(d_task)
```
### 5. Visuzalize Data
```{r}
task <- "Visualize Data"
d_task <- d_times %>%
  filter(task_name == !!task)
plot_burndown(
  d_task,
  beg = as.Date("2021-10-31"), # day before
  end = as.Date("2021-11-07"), # day after
  hrs = 5)
datatable(d_task)
```
### 6. Model
```{r}
task <- "Model"
d_task <- d_times %>%
  filter(task_name == !!task)
plot_burndown(
  d_task,
  beg = as.Date("2021-10-31"), # day before
  end = as.Date("2021-11-07"), # day after
  hrs = 3)
datatable(d_task)
```
### 6. Communnicate
```{r}
task <- "Communnicate"
d_task <- d_times %>%
  filter(task_name == !!task)
plot_burndown(
  d_task,
  beg = as.Date("2021-10-31"), # day before
  end = as.Date("2021-11-07"), # day after
  hrs = 9)
datatable(d_task)
```

